### PR TITLE
Remove Message:exists

### PR DESCRIPTION
**Pull request by HamishSlater**
Expensive resulting in many queries

ERM34902

### CODE REVIEW

**Review by osnard — CHANGES_REQUESTED** [review]
This feature is required fir the MediaWiki Sidebar. We should rather use a modified version of SimpleTreeLinkNode in the book navigation panel

**Comment by HamishSlater** [comment]
MediaWiki Sidebar doesn't seem to use SimpleTreeLinkNode.php or SimpleTreeTextNode.php; it uses RestrictedTextLink.php.

**Comment by HamishSlater** [comment]
Parse Message key in Enhanced Sidebar
https://gerrit.wikimedia.org/r/c/mediawiki/skins/BlueSpiceDiscovery/+/990041

**Review by DvogelHallowelt — APPROVED** [review]

**Comment by DvogelHallowelt** [comment]
Using a modified version of SimpleTreeLinkNode for the book tree-panel is overhead. It is much more easier to modify code like suggested and modify the sidebar implementation in skin

**Review by osnard — APPROVED** [review]

**Comment by osnard** [comment]
See also https://gerrit.wikimedia.org/r/c/mediawiki/skins/BlueSpiceDiscovery/+/990041

**Pull request merged**
